//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mHelp.rc
//
#define IDS_DDRAW_CREATE                1
#define IDS_DDRAW_QUERY                 2
#define IDS_DDRAW_COOPLEVEL             3
#define IDC_ADD_FAVFILE                 3
#define IDC_DOCUMENTATION               3
#define IDC_EVODLG_HELP                 3
#define IDS_DDRAW_SURFACE               4
#define IDS_DDRAW_LOADBMP               5
#define IDC_REMOVE_FAVFILE              5
#define IDS_DDRAW_COLORKEY              6
#define IDC_FAVDLG_HELP                 6
#define IDS_CREATE_MHPDLG               13
#define IDS_CREATE_MULTILISTE           14
#define IDS_TAB_COMPONENT               14
#define IDS_COLUMN_CTRLTYPE             15
#define IDS_COLUMN_PLATFORM             16
#define IDS_COLUMN_CTRLCLASS            17
#define IDS_CREATE_ZAPMENU              18
#define IDS_COLUMN_DLLNAME              18
#define IDS_COLUMN_DLLVERS              19
#define IDS_COLUMN_DLLSTATUS            20
#define IDS_CTRL_INACTIF                21
#define IDS_TOPIC_TODEFINE              21
#define IDS_CTRL_NORADIO                22
#define IDS_QUERY_SERVTREE              24
#define IDS_CREATE_NOPARAM_TASK         25
#define IDS_TASKLISTE_NOREPEAT          26
#define IDS_COPY_FIRST_SEL              27
#define IDS_COPY_PASTE                  28
#define IDS_INCREMENTATION              29
#define IDS_DECREMENTATION              30
#define IDS_CHANGE_STATE                31
#define IDS_EVERY_WHAT                  32
#define IDS_COLUMN_VALUE                33
#define IDS_COLUMN_ROW                  34
#define IDS_FOLDER                      35
#define IDS_DOCUMENT                    36
#define IDS_PARAMETERS                  37
#define IDS_ADD_CONTENTS                38
#define IDS_LIST_OF_CTRL                39
#define IDS_STATE_SELECTION             40
#define IDS_ROW_OF_RADIO                41
#define IDS_STRING_TO_SELECT            42
#define IDS_ENTER_TYPE                  43
#define IDS_FIXED                       44
#define IDS_USER                        45
#define IDS_CANCEL                      48
#define IDS_SAVE                        49
#define IDS_INACTIVE                    50
#define IDS_ACTIVE                      51
#define IDS_CHANGED_STATE               52
#define IDS_NO_STATE                    53
#define IDS_STRING_LIMITE               54
#define IDS_NO_SELECTION                55
#define IDS_FINISH                      56
#define IDS_PARAMETER                   57
#define IDS_TYPE                        58
#define IDS_DESCRIPTION                 59
#define IDS_LIMITED                     60
#define IDS_SHTYPE_I                    71
#define IDS_SHTYPE_R                    72
#define IDS_SHTYPE_C                    73
#define IDS_SHTYPE_B                    74
#define IDS_SHTYPE_S                    75
#define IDS_SHTYPE_IL                   76
#define IDS_SHTYPE_LI                   76
#define IDS_SHTYPE_RL                   77
#define IDS_SHTYPE_LR                   77
#define IDS_SHTYPE_CL                   78
#define IDS_SHTYPE_LC                   78
#define IDS_SHTYPE_BL                   79
#define IDS_SHTYPE_LB                   79
#define IDS_SHTYPE_SL                   80
#define IDS_SHTYPE_LS                   80
#define IDS_CTRL_MENU                   81
#define IDS_CTRL_BUTTON                 82
#define IDS_CTRL_LIST_SINGLE            83
#define IDS_CTRL_COMBO                  84
#define IDS_CTRL_SLIDER                 85
#define IDS_CTRL_EDIT                   86
#define IDS_CTRL_CHECK                  87
#define IDS_CTRL_RADIO                  88
#define IDS_CTRL_LIST_MULTI             89
#define IDS_NEXT                        90
#define IDS_LIST_LIMITED                91
#define IDS_TAB_MHPFILES                92
#define IDS_TAB_CONTENTS                93
#define IDS_TAB_CONFIG                  94
#define IDS_TAB_SEARCH                  95
#define IDS_TAB_INDEX                   96
#define IDS_TAB_FAVORITES               97
#define IDS_TAB_ABOUT                   98
#define IDS_COLUMN_TOPIC                99
#define IDS_COLUMN_FILEPATH             100
#define IDB_CLICK                       101
#define IDD_DLG_PARAM                   101
#define IDS_STATUS_READY                101
#define IDB_PRESS                       102
#define IDS_COLUMN_EVENT                102
#define IDB_MOUSE                       103
#define IDS_COLUMN_KEYWORD              103
#define IDI_ICON_MHP_LOCKED             104
#define IDS_STATUS_NOOPENEDFILE         104
#define IDD_DLG_CFGCTRL                 105
#define IDS_OPEN_FILTER                 105
#define IDI_ICON_RADIO_PARAM            106
#define IDS_STATUS_OPENINGFILE          106
#define IDS_STATUS_UPDATEINDEX          108
#define IDB_TOOLSERV                    109
#define IDS_FILE_ALREADYOPENED          109
#define IDS_STATUS_SEARCHTOPIC          110
#define IDS_STATUS_NORESULT             111
#define IDI_ICON_BOOK                   112
#define IDS_NOREPEAT_OPTION             112
#define IDI_ICON_ENG_HELP               113
#define IDS_COLUMN_REPEATITION          113
#define IDI_ICON_ALLIANCE               114
#define IDS_REMOVEFAV_AUTOASSIST        114
#define IDI_ICON_OP_BOOK                115
#define IDS_SELECT_MHPFILE              116
#define IDS_STATUS_TOPIC                117
#define IDS_WARNING_TREE                118
#define IDD_DLG_MHELP                   119
#define IDS_STOCK_FINISHED              119
#define IDI_ICON_MOUSE                  120
#define IDD_DLG_MESSAGE                 120
#define IDS_EVENT_CUSTOMING             120
#define IDS_CFGCUSTOM_INFO              121
#define IDI_ICON_WARNING                122
#define IDS_NEW_FILTER                  122
#define IDS_UNDEFINED                   123
#define IDD_DLG_FAVSFILE                123
#define IDS_HIDE                        124
#define IDS_SHOW                        125
#define IDD_DLG_MHPEVALUATE             125
#define IDS_TRUE                        126
#define IDS_FALSE                       127
#define IDS_TASK_NOTFOUND               128
#define IDS_NO_FAVSFILE                 129
#define IDS_FAVFILE_EXIST               130
#define IDS_FAVFILE_SAVED               132
#define IDS_FAVFILE_DESTROYED           133
#define IDI_ICON_RSREP                  135
#define IDS_FAVORITE_EXIST              135
#define IDS_FAVFILE_ADDED               136
#define IDS_ERROR_NOPROBLEM             137
#define IDI_ICON_STOPMOUSE              138
#define IDS_ERROR_NOMHPERROR            138
#define IDS_ERROR_READPROCESS           139
#define IDS_ERROR_WRITEPROCESS          140
#define IDS_ERROR_NOINITPROC            141
#define IDI_ICON_PARAM_REP              142
#define IDS_ERROR_MHPFILEPATH           142
#define IDI_ICON_MHP_PARAM              143
#define IDS_ERROR_FAVINDEX              143
#define IDI_ICON_OP_PARAM               144
#define IDS_ERROR_PROCESSKEY            144
#define IDD_DLG_PROGRESS                145
#define IDS_ERROR_FILECORRUPT           145
#define IDD_APROPOS_DLG                 146
#define IDD_DLG_APROPOS                 146
#define IDS_ERROR_CUSTOMINDEX           146
#define IDI_ICON_MHP_TASK               147
#define IDS_ERROR_PARAMINDEX            147
#define IDI_ICON_OP_REP                 148
#define IDS_ERROR_REPEATOPT             148
#define IDS_ERROR_INTTYPE               149
#define IDS_ERROR_REPEATINDEX           150
#define IDS_ERROR_SELINDEX              151
#define IDS_ERROR_INTSELECT             152
#define IDS_ERROR_NEWINTVAL             153
#define IDS_ERROR_NEWBOOLVAL            154
#define IDS_ERROR_INTLISTTYPE           155
#define IDS_ERROR_NOREMOVESEL           156
#define IDS_ERROR_STRTYPE               157
#define IDS_ERROR_STRSELECT             158
#define IDS_ERROR_STRLISTTYPE           159
#define IDS_ERROR_NEWSTRVAL             160
#define IDS_ERROR_SELECTINT             161
#define IDS_ERROR_SELECTSTR             162
#define IDS_ERROR_NOSELECTION           163
#define IDS_LICENSE                     164
#define IDS_MUST_CALL_MAINACTIVE        165
#define IDS_CLOSE                       166
#define IDS_SAVE_SUCCESSFUL             167
#define IDS_SRVMSG_TERMINATE            168
#define IDS_AUTOLNCH_YES                169
#define IDS_CONFIRM_DELETING            170
#define IDS_DELETING_FAILED             171
#define IDS_MHELP_ALOPENNED             172
#define IDS_LOCK_DHPOPEN                173
#define IDS_FORCE_DHPCLOSE              174
#define IDC_LIST_VALUE                  1000
#define IDC_EDIT_ASSOC                  1002
#define IDC_EDIT_TYPE                   1003
#define IDC_APPLY                       1004
#define IDC_EDIT_DECRIT                 1005
#define IDC_EDIT_LIMITE                 1006
#define IDC_COMBO_TYPE                  1007
#define IDC_EDIT_SEARCH                 1007
#define IDC_VALID_PARAM                 1008
#define IDC_LIST_MHPFILES               1008
#define IDC_COLLER                      1009
#define IDC_STATIC_SEARCH               1009
#define IDC_COPIER                      1010
#define IDC_STATIC_VALASSOC             1011
#define IDC_STATIC_NUMREPEAT            1011
#define IDC_REMOVE_PARAM                1013
#define IDC_BUTTON1                     1014
#define IDC_LIST_FAVORITES              1014
#define IDC_SERV_LIST_TASK              1015
#define IDC_STATIC_INDEX                1015
#define IDC_BTN_CONFIG                  1016
#define IDC_EDIT_MSG                    1016
#define IDC_RADIO_ONE                   1017
#define IDC_TAB_MHELP                   1017
#define IDC_BTN_MOVEDOWN                1017
#define IDC_RADIO_TWO                   1018
#define IDC_BTN_MOVEUP                  1018
#define IDC_WHAT_EDIT                   1019
#define IDC_PARAM_LIST_TASK             1019
#define IDC_SLIDER_SPEED                1020
#define IDC_EDIT_CTRL                   1020
#define IDC_BTN_HIDESHOW                1020
#define IDC_STATIC_STATUS               1022
#define IDC_STATUS                      1023
#define IDC_EDIT_DESCRIPTION            1025
#define IDC_EDIT_TYPEFLAG               1026
#define IDC_EDIT_BORNE                  1027
#define IDC_STATIC_ABOUT                1027
#define IDC_STATIC_RADIO                1028
#define IDC_LOAD_PROGRESS               1028
#define IDC_TREEVIEW_RS                 1029
#define IDC_CHECK_EXT                   1029
#define IDC_STATIC_SELEVENT             1030
#define IDC_RADIO_THREE                 1031
#define IDC_FRAME_MODE                  1031
#define IDC_CHECK_MHELP                 1032
#define IDC_CHECK_ASSIST                1033
#define IDC_EDIT_RS                     1034
#define IDC_STATIC_ICON                 1035
#define IDC_HIDDEN_TREEVIEW             1035
#define IDC_FRAME_CURSORSPEED           1036
#define IDC_EDIT_VIEWMSG                1037
#define IDC_STATIC_MOUSEICON            1037
#define IDC_START                       1038
#define IDC_TASK_LIST                   1039
#define IDC_PROGRESS1                   1040
#define IDC_ADD_MHPFILES                1040
#define IDC_PROGRESS_MHPSAVE            1040
#define IDC_PROGRESS_STATUS             1041
#define IDC_REMOVE_MHPFILES             1041
#define IDC_SEARCH                      1042
#define IDC_HIDE_INDEXLIST              1043
#define IDC_STATIC_EVENT                1044
#define IDC_CREATE_ADD                  1045
#define IDD_DLG_MHPSERV                 1046
#define IDC_HIDE_SEARCHLIST             1046
#define IDC_NEXT                        1047
#define IDC_ADD_FAVORITES               1047
#define IDC_FRAME_WHAT                  1048
#define IDC_REMOVE_FAVORITES            1048
#define IDC_LAST                        1049
#define IDC_FRAME_REPEAT                1049
#define IDC_VIEW_RSTREE                 1050
#define IDC_SAVE_AUTOASSIST             1050
#define IDC_EDIT_NUMREPEAT              1051
#define IDC_BTN_ADD                     1052
#define IDC_STATIC_SLOW                 1052
#define IDC_STATIC_FAST                 1053
#define IDC_NEW_MHPSAVE                 1053
#define IDC_EDIT_INDEX                  1054
#define IDC_OPEN_MHPSAVE                1054
#define IDC_EDIT_EVENT                  1055
#define IDC_REMOVE_MHPSAVE              1055
#define IDC_LIST_INDEX                  1056
#define IDC_MHELP_ICON                  1057
#define IDC_SET_INDEX                   1058
#define IDC_LIST_SEARCH                 1059
#define IDC_SET_SEARCH                  1060
#define IDC_SET_FAVORITES               1061
#define IDC_FRAME_SEPVERT               1062
#define IDC_FRAME_MHELPVERS             1063
#define IDC_FRAME_SEPHORY               1064
#define IDC_STATIC_REPEATITION          1065
#define IDC_SAVE_FAVORITES              1066
#define IDC_STATIC_REPEATCFG            1067
#define IDC_HIDE_FAVLIST                1068
#define IDC_OPEN_FAVORITES              1069
#define IDC_STATIC_AUTOASSIST           1070
#define IDC_STATIC_AUTOASSISTCFG        1071
#define IDC_FRAME_AUTOASSIST            1072
#define IDC_RESET_AUTOASSIST            1073
#define IDC_DESTROY                     1074
#define IDC_STATIC_FAVROW               1075
#define IDC_EDIT_AUTOASSIST             1076
#define IDC_RADIO_FAV                   1077
#define IDC_RADIO_AUTOASSIST            1078
#define IDC_STATIC_MHPICON              1079
#define IDC_STATIC_SEPHOR               1080
#define IDC_LIST_MHPSAVE                1081
#define IDC_STATIC_STATE                1082
#define IDC_CURRENT_STATUS              1083
#define IDC_WHAT_RADIO                  1084
#define IDC_FRAME_TREEITEM              1084
#define IDC_RADIO_FOLDER                1085
#define IDC_RADIO_DOC                   1086
#define IDC_RADIO_PARAM                 1087
#define IDC_LIST_FAVSFILE               1088
#define IDC_EDIT_FILENAME               1090
#define IDC_STATIC_FILENAME             1091
#define IDC_STATIC_MAXDELAY             1092
#define IDC_STATIC_EDITDELAY            1097
#define IDC_EDIT_HOUR                   1098
#define IDC_EDIT_MINUTE                 1099
#define IDC_STATIC_POINTS               1100
#define IDC_EDIT_LICENSE                1103
#define IDC_TEST                        1104
#define IDC_STATIC_RESTDAY              1105
#define IDC_STATIC_NUMDAY               1106
#define IDC_BUTTON_HELP                 1107
#define IDC_STATIC_SELECTION            1109
#define IDC_LISTVIEW_COMPONENT          1110
#define IDC_STATIC_CTRLMGMT             1111
#define IDC_TOPIC_TREE                  1113
#define IDC_HIDDEN_TREE                 1114
#define IDC_HIDDEN_SERVTREE             1114
#define IDB_UNPRESS                     8011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
