//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mHpWPFCheckBox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mHpWPFCheckBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mHpCheckBox {
            get {
                object obj = ResourceManager.GetObject("mHpCheckBox", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox WPF.
        /// </summary>
        internal static string RS_CHECKBOX_DESC {
            get {
                return ResourceManager.GetString("RS_CHECKBOX_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        internal static string RS_CHECKBOX_NAME {
            get {
                return ResourceManager.GetString("RS_CHECKBOX_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.5.
        /// </summary>
        internal static string RS_CHECKBOX_VERS {
            get {
                return ResourceManager.GetString("RS_CHECKBOX_VERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change d&apos;état.
        /// </summary>
        internal static string RS_STATE_CHANGECHECK {
            get {
                return ResourceManager.GetString("RS_STATE_CHANGECHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activé.
        /// </summary>
        internal static string RS_STATE_CHECKED {
            get {
                return ResourceManager.GetString("RS_STATE_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indéterminé.
        /// </summary>
        internal static string RS_STATE_INDETERMINATE {
            get {
                return ResourceManager.GetString("RS_STATE_INDETERMINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivé.
        /// </summary>
        internal static string RS_STATE_UNCHECKED {
            get {
                return ResourceManager.GetString("RS_STATE_UNCHECKED", resourceCulture);
            }
        }
    }
}
