//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mHpCtrl.rc
//
#define IDS_COLUMN_TYPE                 1
#define IDS_COLUMN_ROW                  2
#define IDC_CONTINUE_BTN                2
#define IDS_COLUMN_STATE                3
#define IDC_ADD_MULTILIST               3
#define IDS_COLUMN_APPLI                4
#define IDC_REMOVE_MULTILIST            4
#define IDS_TAB_COMMON                  5
#define IDC_LINK_ITEM                   5
#define IDS_TAB_ABOUT                   6
#define IDC_UNLINK_ITEM                 6
#define IDS_DDRAW_CREATE                7
#define IDS_D2D_END_DRAW                7
#define IDS_DDRAW_QUERY                 8
#define IDS_UNDEFINED_STATE             8
#define IDS_DDRAW_COOPLEVEL             9
#define IDS_CTLMGMT_LOAD_ERROR          9
#define IDS_DDRAW_SURFACE               10
#define IDS_CTLMGMT_LOAD_SUCCEED        10
#define IDS_DDRAW_LOADBMP               11
#define IDS_CTLMGMT_LOAD_NOCLASS        11
#define IDS_DDRAW_COLORKEY              12
#define IDS_CTLMGMT_LOAD_NOVERSION      12
#define IDS_STRING_CTRL                 13
#define IDS_CTRL_INACTIF                14
#define IDS_TASKLISTE_NOREPEAT          15
#define IDS_TASKLISTE_CREATE            16
#define IDS_CREATE_TASK                 17
#define IDS_CREATE_TASK1                17
#define IDS_CTRL_MENU                   18
#define IDS_PRODUCT_MENU                19
#define IDS_VERSION_MENU                20
#define IDS_DESCRIPTION_MENU            21
#define IDS_CTRL_BUTTON                 22
#define IDS_PRODUCT_BUTTON              23
#define IDS_VERSION_BUTTON              24
#define IDS_DESCRIPTION_BUTTON          25
#define IDS_CTRL_LIST                   26
#define IDS_PRODUCT_LIST                27
#define IDS_VERSION_LIST                28
#define IDS_DESCRIPTION_LIST            29
#define IDS_CTRL_COMBO                  30
#define IDS_PRODUCT_COMBO               31
#define IDS_VERSION_COMBO               32
#define IDS_DESCRIPTION_COMBO           33
#define IDS_CTRL_SLIDER                 34
#define IDS_PRODUCT_SLIDER              35
#define IDS_VERSION_SLIDER              36
#define IDS_DESCRIPTION_SLIDER          37
#define IDS_CTRL_EDIT                   38
#define IDS_PRODUCT_EDIT                39
#define IDS_VERSION_EDIT                40
#define IDS_DESCRIPTION_EDIT            41
#define IDS_VIEW_CHANGEEXE              42
#define IDS_VIEW_MENU                   43
#define IDS_VIEW_BUTTON                 44
#define IDS_VIEW_LIST_SINGLE            45
#define IDS_VIEW_COMBO                  46
#define IDS_VIEW_SLIDER                 47
#define IDS_VIEW_EDIT                   48
#define IDS_VIEW_CHECK                  49
#define IDS_VIEW_RADIO                  50
#define IDS_VIEW_LIST_MULTI             51
#define IDS_CREATE_MULTILISTE           52
#define IDS_NO_STATE                    53
#define IDS_INACTIVE                    54
#define IDS_NO_SELECTION                55
#define IDS_ACTIVE                      56
#define IDS_CHANGED_STATE               57
#define IDS_D2D_CREATE_DC               58
#define IDS_D2D_COMPATIBLE_DC           59
#define IDS_CTRL_CHANGEEXE              60
#define IDS_INDETERMINATE_STATE         61
#define IDS_WARNING_NOSAVE              62
#define IDS_TAB_STATE                   63
#define IDS_VALUE_ASSIGNED              64
#define IDS_VALUE_INDETERMINATE         65
#define IDS_SLIDER_VALUE                66
#define IDS_VALUE_CONTENTS              67
#define IDS_VALUE_DESCRIPTION           68
#define IDS_VALUE_STRSEL                69
#define IDS_VALUE_STRSELS               70
#define IDS_VALUE_CTRLROW               71
#define IDS_COLUMN_UNLINKED             72
#define IDS_CTRL_MAXRADIO1              73
#define IDS_CTRL_MAXRADIO2              74
#define IDS_ADD_FINISHED                75
#define IDS_ADD_CUSTOMING               76
#define IDS_EXE_NOTFOUND                77
#define IDS_COLUMN_VISIBLE              78
#define IDS_STRING_TRUE                 79
#define IDS_DIFF_WINDOW                 80
#define IDS_VIEW_TABCTRL                81
#define IDS_PRODUCT_TABCTRL             82
#define IDS_VERSION_TABCTRL             83
#define IDS_DESCRIPTION_TABCTRL         84
#define IDS_CTRL_TABCTRL                85
#define IDS_CREATE_TASK2                86
#define IDS_TASKLISTE_DIFFEXE           87
#define IDS_STOP_PROCESS                88
#define IDS_MAX_DELAY                   89
#define IDS_CHARACTERS                  90
#define IDS_PRODUCT_LISTVIEW            91
#define IDS_VERSION_LISTVIEW            92
#define IDS_DESCRIPTION_LISTVIEW        93
#define IDS_CTRL_LISTVIEW               94
#define IDS_VIEW_LISTVIEW               95
#define IDS_VIEW_TREEVIEW               96
#define IDS_CTRL_TREEVIEW               97
#define IDS_PRODUCT_TREEVIEW            98
#define IDS_VERSION_TREEVIEW            99
#define IDS_DESCRIPTION_TREEVIEW        100
#define IDB_CLICK                       101
#define IDS_STRING_FALSE                101
#define IDB_PRESS                       102
#define IDS_VIEW_TOOLBAR_BTN            102
#define IDB_MOUSE                       103
#define IDS_CTRL_TOOLBAR                103
#define IDI_ICON_MENU                   104
#define IDS_PRODUCT_TOOLBAR             104
#define IDD_DLG_CFGCTRL                 105
#define IDS_VERSION_TOOLBAR             105
#define IDS_DESCRIPTION_TOOLBAR         106
#define IDI_ICON_EXE                    107
#define IDS_VIEW_TOOLBAR_CHK            107
#define IDS_VIEW_TOOLBAR_RAD            108
#define IDI_ICON_BUTTON                 109
#define IDS_VIEW_TOOLBAR_CBO            109
#define IDI_ICON_CHECK                  110
#define IDS_VIEW_TOOLBAR_DDW            110
#define IDI_ICON_RADIO                  111
#define IDS_CTRL_NOSTATE                111
#define IDI_ICON_COMBO                  112
#define IDS_VALUE_COMMANDLINE           112
#define IDI_ICON_EDIT                   113
#define IDS_D2D_COMPATIBLE_BMP          113
#define IDS_D2D_BITBLT                  114
#define IDI_ICON_MULTILIST              115
#define IDS_D2D_SCREEN_BUFFER           115
#define IDI_ICON_SINGLELIST             116
#define IDS_D2D_CREATE_BBUFFER          116
#define IDI_ICON_SLIDER                 117
#define IDS_D2D_COPY_BBUFFER            117
#define IDI_ICON_WARNING                118
#define IDS_D2D_CREATE_CURSOR           118
#define IDS_D2D_LOAD_CURSOR             119
#define IDD_DLG_MESSAGE                 120
#define IDI_ICON_SEP                    120
#define IDS_D2D_GET_CBUFFER             120
#define IDS_D2D_COPY_CBUFFER            121
#define IDI_ICON_RICHEDIT               122
#define IDS_D2D_FACTORY                 122
#define IDI_ICON_LISTVIEW               123
#define IDS_D2D_RENDERTARGET            123
#define IDS_D2D_RT_BINDDC               124
#define IDI_ICON_TABCTRL                125
#define IDS_CTLMGMT_LOAD_NONAME         125
#define IDI_ICON_TOOLBAR                126
#define IDS_ERROR_GETSYSFOLDER          126
#define IDI_ICON_TREEVIEW               127
#define IDS_HTML_SUBMIT                 127
#define IDB_ALTGR_PRESS                 128
#define IDS_HTML_TASKDESC               128
#define IDB_SHIFT_PRESS                 129
#define IDS_HTML_STATEDESC              129
#define IDB_DBLCLICK                    134
#define IDB_DBCLICK                     135
#define IDR_WAVE_PRESS                  137
#define IDR_WAVE_UNPRESS                140
#define IDI_ICON_DEFAULT                146
#define IDC_CTRL_TAB                    1001
#define IDC_CTRL_ICON                   1002
#define IDC_STATIC_MSG                  1003
#define IDC_STATIC_CTRL                 1004
#define IDC_STATIC_CLASS                1005
#define IDC_STATIC_PRODUCT              1005
#define IDC_VIEW_CLASS                  1006
#define IDC_COMBO_TYPE                  1007
#define IDC_STATIC_VERSION              1008
#define IDC_VERSION_CTRL                1009
#define IDC_FRAME_ABOUTCFG              1010
#define IDC_STATIC_DESCRIPTION          1011
#define IDC_DESCRIPTION_CTRL            1012
#define IDC_RADIO_VIEWMSG_STOP          1013
#define IDC_RADIO_VIEWMSG_CONTINUE      1014
#define IDC_RADIO_NOMSG                 1015
#define IDC_EDIT_MSG                    1016
#define IDC_STATIC_STATETYPE            1017
#define IDC_STATIC_LIMITE               1018
#define IDC_STATIC_STATEDESCRIPTION     1019
#define IDC_STATIC_STATEINFO            1020
#define IDC_APPLY                       1021
#define IDC_FRAME_STATE                 1022
#define IDC_CHECK_ACTIVE                1023
#define IDC_CHECK_INACTIVE              1024
#define IDC_EDIT_DESCRIPTION            1025
#define IDC_EDIT_TYPEFLAG               1026
#define IDC_EDIT_BORNE                  1027
#define IDC_CHECK_CHANGEINT             1028
#define IDC_STATIC_STATE                1029
#define IDC_EDIT_STATE                  1030
#define IDC_SLIDER_CFG                  1031
#define IDC_RADIO_FIXED                 1032
#define IDC_RADIO_USER                  1033
#define IDC_MULTI_EDIT                  1034
#define IDC_LIST_RADIO                  1036
#define IDC_EDIT_VIEWMSG                1037
#define IDC_RADIO_DELAYMSG              1037
#define IDC_EDIT_NOSTATE_MSG            1038
#define IDC_CHECK_NOSTATE               1040
#define IDC_LAUNCH_DOC                  1043
#define IDC_LISTBOX_MULTILIST           1044
#define IDB_UNPRESS                     8011

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
